# Generated by Django 2.2 on 2021-04-13 09:10

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0003_auto_20210413_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 9, 10, 51, 185840, tzinfo=utc)),
        ),
    ]
