# Generated by Django 2.2 on 2021-05-13 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20210426_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 16, 10, 13, 876840, tzinfo=utc)),
        ),
    ]
