# Generated by Django 2.2 on 2021-05-14 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20210513_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 5, 33, 14, 573211, tzinfo=utc)),
        ),
    ]
